resources:
- ../backends/multistore

patches:
- target:
    kind: OpenStackControlPlane
  patch: |-
    - op: replace
      path: /spec/glance/template/customServiceConfig
      value: |
        [DEFAULT]
        debug=True
        enabled_backends = ceph-0:rbd,ceph-1:rbd,swift-0:swift
        enabled_import_methods = web-download,copy-image
        [glance_store]
        default_backend = ceph-1
        [ceph-0]
        rbd_store_ceph_conf = /etc/ceph/ceph-0.conf
        store_description = "RBD backend"
        rbd_store_pool = images
        rbd_store_user = openstack
        [ceph-1]
        rbd_store_ceph_conf = /etc/ceph/ceph-1.conf
        store_description = "RBD backend 1"
        rbd_store_pool = images
        rbd_store_user = openstack
        [swift-0]
        swift_store_create_container_on_put = True
        swift_store_auth_version = 3
        swift_store_auth_address = {{ .KeystoneInternalURL }}
        swift_store_key = {{ .ServicePassword }}
        swift_store_user = service:glance
        swift_store_endpoint_type = internalURL
        swift_store_region = {{ .Region }}
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
