# ATTENTION: After applying this OpenShift nodes will reboot, because of the `MachineConfig` changes and will take a while to recover.

  # Secret used by the glance backend
  # Whole OpenStack deployment using a Cinder NVMe-TCP LVM backend with application credential authentication
resources:
- https://github.com/openstack-k8s-operators/cinder-operator/config/samples/backends/lvm/nvme-tcp

components:
- ../glance-common-appcred
patches:
- target:
    kind: OpenStackControlPlane
    name: .*
  patch: |-
    - op: add
      path: /spec/applicationCredential
      value:
        enabled: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
