---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-glance-openstack-org-v1beta1-glance
  failurePolicy: Fail
  name: mglance-v1beta1.kb.io
  rules:
  - apiGroups:
    - glance.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - glances
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-glance-openstack-org-v1beta1-glanceapi
  failurePolicy: Fail
  name: mglanceapi-v1beta1.kb.io
  rules:
  - apiGroups:
    - glance.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - glanceapis
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-glance-openstack-org-v1beta1-glance
  failurePolicy: Fail
  name: vglance-v1beta1.kb.io
  rules:
  - apiGroups:
    - glance.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - glances
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-glance-openstack-org-v1beta1-glanceapi
  failurePolicy: Fail
  name: vglanceapi-v1beta1.kb.io
  rules:
  - apiGroups:
    - glance.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - glanceapis
  sideEffects: None
