apiVersion: glance.openstack.org/v1beta1
kind: GlanceAPI
metadata:
  name: glance
spec:
  serviceUser: glance
  containerImage: quay.io/tripleotraincentos8/centos-binary-glance-api:current-tripleo
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseUser: glance
  debug:
    dbSync: false
    service: false
  preserveJobs: false
  replicas: 1
  storageRequest: 10G
  secret: glance-secret
